
let stock_productos = [
    {id: 1, nombre: "Alimentación inteligente", tipo: "Libro", descr: "El milagro de alimentarse bien y conservar un peso ideal está al alcance de la mano. Hay que comer con la cabeza.", precio: 2800, cantidad: 1, imagen: "../IMG/alimentacion_inteligente.webp"},
    {id: 2, nombre: "100 recetas saludables", tipo: "Libro", descr: "Este libro reúne más de 100 propuestas saludables y equilibradas que nos demuestran que se puede comer sano, cuidarse y disfrutar haciéndolo", precio: 1250, cantidad: 1, imagen: "../IMG/100_recetas_saludables.webp"},
    {id: 3, nombre: "Alimentación para sanar", tipo: "Libro", descr: "¿Estamos comiendo de forma correcta para cubrir las necesidades de nuestro cuerpo? ¿Te gustaría tener energía suficiente, verte bien y estar saludable?", precio: 4250, cantidad: 1, imagen: "../IMG/alimentacion_para_sanar.webp"},
    {id: 4, nombre: "Asesoramiento Nutricional - Doctora González", tipo: "Servicio", descr: "Sesiones de asesoramiento nutricional por parte de la doctora González: Diágnostico, detección de alteraciones, plan de acción y monitoreo.", precio: 3500, cantidad: 1, imagen: "../IMG/consulta_dietetica.jpg"},
    {id: 5, nombre: "Asesoramiento Nutricional - Licenciada Santamaría", tipo: "Servicio", descr: "Sesiones de asesoramiento nutricional mediado por la licenciada Santamaría: Licenciada en nutrición y deportóloga. Plan nutricional y rutinas de ejercicio.", precio: 3800, cantidad: 1, imagen: "../IMG/asesoramiento_nutri.jpg"},
    {id: 6, nombre: "Asesoramiento nutricional - Doctor Giménez", tipo: "Servicio", descr: "Sesiones personalizadas guiadas por el doctor Giménez. Experto en alteraciones metabólicas y problemas de la alimentación.", precio: 3200, cantidad: 1, imagen: "../IMG/asesoramiento-nutricional.jpg"},
    {id: 7, nombre: "Whey. X-Pro", tipo: "Suplemento", descr: "Suplemento en polvo ENA Sport Whey X-Pro proteína sabor vanilla ice cream en pote de 907g. Cantidad de porciones: 30 de 33 gramos.", precio: 8479, cantidad: 1, imagen: "../IMG/whey.webp"},
    {id: 8, nombre: "Ensure", tipo: "Suplemento", descr: "Suplemento en polvo Ensure Base carbohidratos sabor vainilla en caja de 1.2kg. Cantidad de porciones: 22 unidades de 53.8 gramos", precio: 7290, cantidad: 1, imagen: "../IMG/ensure.webp"},
    {id: 9, nombre: "Omega 3", tipo: "Suplemento", descr: "Suplemento en cápsulas blandas InnovaNaturals Omega 3. Ayuda a fortalecer el sistema inmunológico. Contiene: 60 unidades de 60 gramos.", precio: 8489, cantidad: 1, imagen: "../IMG/omega3.webp"},
];